### ISSUE TITLE
Game deck and board initialization

### ISSUE THREAD

**Issue by xaelleone** [xaelleone/spondue#3]
Partition the incoming cards into tiers, shuffle the decks, and deal cards for the board.

**Comment by katiehdunn** [comment]
the first two of these are done, but not prettily / feel free to redo. not sure if the board should be a list 12 long or 3 separate parts by tier; I suspect tiers might be a bit annoying longer-term

**Comment by dominickjoo** [comment]
given that the tiers are actually separate (will be drawing from different pools) i think it makes sense not to have a list of 12 cards

**Comment by xaelleone** [comment]
This is done with this commit: https://github.com/xaelleone/spondue/commit/8c8944e2f537cfbab19d8ad22b0ad7cf0ad01ad9
